# Generated by Django 6.1.1 on 2026-09-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, help_text='Amazon Standard Identification Number (10-char product ID).', max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('topic', models.CharField(blank=True, default='', help_text='The trend topic that led to this product.', max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
